### ISSUE TITLE
Questions about Apple TV video players for content served by Apple Home Sharing.

### ISSUE THREAD

**Issue by loshlee** [donmelton/more-video-transcoding#12]
I have a library of movies that are served to Apple TV through Apple Home Sharing. Many or possibly most of them were transcoded using Video Transcoding and More Video Transcoding or methods mostly derived therefrom. I didn't want to hijack the Color Banding question recently added to the Issues for More Video Transcoding, so I'm asking a new one. Lisa Melton suggested using Plex player or anything other than Apple TV's built in player to play content shared through a home media server. My question is, "What other reliable player apps available for Apple TV can access Apple's Home Sharing?"

I considered abandoning Home Sharing once after it seemed to become unreliable for no reason. At that point, I temporarily configured another media server called Universal Media Server and accessed it using an Apple TV add-on called 8Player, which seemed to work well. I've since reverted to Home Sharing, which appears to be working better now. The reason I went back to Home Sharing is that changing server solutions would be very time consuming. 

Thanks.

**Comment by lisamelton** [comment]
@loshlee I'm sorry, but I have no idea what other reliable player apps are available for Apple TV which can access Apple's Home Sharing. I don't have an Apple TV. The Apple media ecosystem is extremely constrained in its capabilities. This is why I always recommend people use Plex. Plex can handle almost any kind of media. And Plex does work on Apple TV. But I don't know if it's compatible with Home Sharing.

**Comment by loshlee** [comment]
Thanks. That's my dilemma, then. I can probably share Matroska using Universal Media Server, but is it worth the trouble to migrate?

**Comment by lisamelton** [comment]
@loshlee I don't know what "Universal Media Server" is so, again, no idea. 🤷‍♀️

**Comment by weaverm** [comment]
@loshlee I assume when you say Apple Home Sharing, that means you're putting your files into iTunes (or now the AppleTV app) and using the orange Home Sharing app on AppleTV to access that stuff?

The app Infuse by a company called Firecore works pretty well on AppleTV. In some ways I like it better than Plex's client app. Infuse can point at a Plex server, or a file share setup on your computer. I do not know, but it might be possible that you could turn on file sharing for where ever your media is stored on your computer (aka in your iTunes library) and then use Infuse on your AppleTV to watch those files.

I used to put stuff in iTunes and use Apple Home Sharing, but a couple years ago I setup a Plex server and have been happier for it. In fact, I'm about to migrate my setup to my third Plex server. I've helped friends setup Plex servers on old computers and their lives are better for it.

**Comment by loshlee** [comment]
Thanks. I had some problems with Home Sharing on my bridged ethernet/wi-fi network last year, so I tried something called Universal Media Server, and that worked pretty well. Although VLC media client for Apple TV was recommended by the author of Universal Media Server, I had much better results using the free version of 8Player. I can connect to my Home Sharing media using 8Player also, but they don't look nearly as acceptable as when shared from Universal Media Server,  which uses DLNA, if I remember correctly. I ended up going back to Home Sharing, which seems to be working better these days.

Anyway, I would like to try Infuse and Plex sometime when I'm mentally up to the configuration tasks. What I haven't managed yet with any configuration other than Home Sharing and Apple player for Apple TV is incorporating recognition of my metadata. I'm sure Infuse and Plex probably provide that, but I anticipate some considerable configuration tasks. Is that the case? The Apple system appears to require no special configuration for it, and looks a lot better than anything I ever got out of VLC, although I may not have worked out the correct filters to optimally play 24 fps, which defines most of my content. It doesn't seem to be any of the built-in settings, at least. Anyway, I guess there are forums for home theater that would be more appropriate for discussing these sorts of topics. Thanks again.

L

**Comment by weaverm** [comment]
Plex downloads metadata from well known places on the internet. Namely, themoviedb.org and/or thetvdb.com. The only trick to it really is learning to name the files and folders the way Plex wants (which is a reasonably logical way to name things). Naming things correctly helps the scanner identify items so all the metadata can be populated correctly.

If you have literally any old computer lying around there's probably a Plex server build for it. My first Plex server was on a Raspberry Pi 4 with a USB drive attached. Having a Plex server does not mean you have to instantly abandon Home Sharing. Find any old machine, put Plex server on it, and set it up with just a handful of movies to try it out. It is surprisingly easy, especially if your old computer is running macOS or Windows.

**Comment by weaverm** [comment]
@lisamelton Out of curiosity, what client hardware are you using if not an AppleTV? Are you using the Ugoos am6b+ with CoreELEC? Something else?

**Comment by loshlee** [comment]
> @loshlee I don't know what "Universal Media Server" is so, again, no idea. 🤷‍♀️

[https://www.universalmediaserver.com](https://www.universalmediaserver.com)
