### ISSUE TITLE
MP4 output with two-pass-transcode.rb?

### ISSUE THREAD

**Issue by briangoodman** [donmelton/more-video-transcoding#15]
Is it possible to output MP4 rather than MKV with the two-pass-transcode script?

**Comment by lisamelton** [comment]
Yes. Just add `--extra format=av_mp4` to your command line.

Does that work for you?

**Comment by briangoodman** [comment]
Will try that now.

**Comment by briangoodman** [comment]
Handbrake version:
HandBrakeCLI 1.81

My command line:
two-pass-transcode.rb ghost.mkv --add-audio all --add-subtitle all --extra format=av_mp4

The error code:
/usr/local/bin/two-pass-transcode.rb: unsupported HandBrakeCLI option name: format

**Comment by lisamelton** [comment]
@briangoodman You can't add image-based subtitles from DVDs or Blu-ray Discs to an MP4 format file. That's why it's failing. Remove `--add-subtitle all` from your command line and try again.

**Comment by briangoodman** [comment]
Will retry first thing tomorrow. Thanks for the quick reply.

**Comment by briangoodman** [comment]
Until tomorrow, a curiosity question. I’ve transcoded almost 400 foreign language films with other-transcode using the same command line and my MP4s contain the subtitles. Does other-transcode do something different to handbrake with respect to subtitle files?

(The reason I use MP4 is superior metadata support in Plex)

**Comment by lisamelton** [comment]
@briangoodman As to the difference between the two different tools, it depends on the input file and which options you're using. Also remember that `other-transcode` is based on `ffmpeg` and will simply ignore subtitles it doesn't like.

As for which format works better in Plex, I've always used MKV because it's much more compatible, flexible and, as far as I'm concerned, it supports metadata better. Your mileage may vary, of course.

**Comment by briangoodman** [comment]
Tried an input file with no subtitles, still get the same error message. Removing --extra format=av_mp4 and transcoding to mkv works perfectly.

**Comment by briangoodman** [comment]
... and a clarification regarding MKV, metadata, and Plex:

The metadata support in MKV may be better than in MP4, but the problem is that Plex, In spite of numerous requests, only reads a limited subset of MKV metadata - title, subtitle, language, and audio track title.

So you might ask why I need more metadata that that. For 75% of my Plex movie library, I rely on Plex to correctly parse the filename information to provide the correct movie information. But since I am on the OCD 12 step program, there are some items where I want more control. For example:
- the Plex agent tags any film related to music as Music and I want a separate genre for Musicals. 
- the Plex agent sometimes tags individual films in a series (like James Bond) with different genre tags and I want them to be the same (yes, serious OCD).
- there are a few genres that I've added beyond what the Plex agent tags to enable additions to the Categories tab.

I would gladly switch over to MKV transcoded files if Plex did read the metadata I need, as per your advice, I've kept the original MakeMKV source files so I could re-transcode in the future, and tagging the original MKV means I would no longer have to individually tag MP4 output files for 25% of my library, relying on the tags to carry over to the transcoded file.

**Comment by lisamelton** [comment]
@briangoodman I'm sorry you're still having the same problem. Can you give me more information about your platform and your input file? A dump from MediaInfo would be ideal. Thanks.

**Comment by briangoodman** [comment]
I’m running the script on a 2012 i7 Mac Mini running Catalina. 

To rule out any issues with old hardware and operating systems, I will install the scripts on my wife’s 2018 i3 Mac Mini running Sonoma. 

So I’d like to leave this open while I remove the hardware/operating system age variables, which will take awhile.

**Comment by loshlee** [comment]
Could you use this on your .mkv files after they're created? (You need ffmpeg installed, of course.)
`fmpeg -i movie.mkv -c copy movie.m4v` or `fmpeg -i movie.mkv -c copy movie.mp4`

**Comment by briangoodman** [comment]
I performed the ffmpeg conversion as above. Attached are 4 mediainfo screenshots:
- the original MakeMKV file
- the two-pass transcode of the original MakeMKV file to MKV
- the ffmpeg conversion of the two-pass transcoded file to MP4
- the other-transcode of the original MakeMKV file to MP4

![1 MakeMKV file mediainfo](https://github.com/user-attachments/assets/f19e07f9-53d4-4d9a-a38e-25650655e875)
![2 two pass transcode of MakeMKV file mediainfo](https://github.com/user-attachments/assets/ac5570f7-4eaf-46e3-96c3-04a64b6362e4)
![3 ffmpeg conversion of two-pass transcoded file mediainfo](https://github.com/user-attachments/assets/92de886d-6e5d-4834-be0f-c666c374b2c3)
![4 other transcode of original MakeMKV file mediainfo](https://github.com/user-attachments/assets/c43564f1-5f0f-4083-aab8-1df3bbe7cf9f)

P.S. I note that both two-pass transcode to MKV and other-transcode to MP4 successfully incorporated all the VobSub files and the french audio track while ffmpeg did not.

**Comment by briangoodman** [comment]
The above was done on my 2012 Mac Mini i7 Catalina.

**Comment by briangoodman** [comment]
Just tried the two-pass-transcode with all the script dependencies updated and HandBrakeCLI 1.8.1 on my Sonoma Mac Mini i3. The "--extra format=av_mp4" suffix returns the same error.

**Comment by lisamelton** [comment]
@briangoodman My sincere apologies for wasting your time. The reason it's not working is that I haven't yet checked in the change to enable support for `format`. I'll do that in the next few days.

In my defense, my local version of the completely rewritten version of `transcode-video`, which is based on `two-pass-transcode.rb`, has this change.

**Comment by briangoodman** [comment]
@lisamelton 

No need to apologize. Next to your efforts to create and support these scripts, the small amount of time I spent is a rounding error.
