### ISSUE TITLE
"extra" help

### ISSUE THREAD

**Issue by loshlee** [donmelton/more-video-transcoding#2]
I'm hoping to get a little "extra" help with more-video-transcoding.

Can I use `--extra NAME[=VALUE]` to specify detelecine? What's the syntax? Would it be 
`--extra --filter[detelecine]`

Thanks.

**Comment by lisamelton** [comment]
@loshlee Just add `--extra detelecine` or `-x detelecine` to your command line.

**Comment by loshlee** [comment]
Great! Thanks!

**Comment by lisamelton** [comment]
@loshlee BTW, if you *do* use the `detelecine` filter, it's also a *really* good idea to explicitly set the frame rate and control like this: `-x detelecine -x rate=23.976 -x cfr`.

**Comment by loshlee** [comment]
Thanks! And to get .m4v or .mp4 output?

**Comment by lisamelton** [comment]
@loshlee It's super easy! Just re-write the script. :trollface:

Seriously, you can convert it afterwards with `ffmpeg` if you *really* need that crappy format. Do you want the command for that?

**Comment by loshlee** [comment]
Thanks! No, I can manage that, but I'm sort of married to Apple Home Sharing, and until that starts accepting .mkv (I haven't checked this month), I'll either have to convert the files , or learn how to do Plex or something.

**Comment by lisamelton** [comment]
@loshlee Ah. Well, don't bother to check. Apple hates MKV. 🤷‍♀️

The command, BTW, really *is* simple: `ffmpeg -i input.mkv -c copy output.mp4`

Just don't have an image-based subtitle or audio format that MP4 doesn't like or it will fail.

**Comment by loshlee** [comment]
Yeah, I'll  wait until it's .mp4 to add subtitles. I finally broke down and bought this great app called Subtitle Studio. I wrote an AppleScript for it that lets me limit YouTube subtitles to 1 line only (getting rid of repeated lines), if you ever need something like that.

**Comment by lisamelton** [comment]
@loshlee Thanks. I use "Subtitle Edit" on Windows on the rare occasion when I need something like that. BTW, it's free.

**Comment by lisamelton** [comment]
@loshlee BTW, do you want to close this now? Or is there anything else I can help you with?

**Comment by loshlee** [comment]
That's it. I'll close it.
