### ISSUE TITLE
Batch job

### ISSUE THREAD

**Issue by geddy76** [donmelton/more-video-transcoding#9]
Hi, Lisa! I’ve got these new scripts working on my new 4k discs. Is there a way to do batch jobs with them? I know with the previous scripts we could, but these seem to run a bit differently. I’d like to be able to submit a few movs and then walk away for a week. 

Thanks for the continued development in this space.

**Comment by lisamelton** [comment]
@geddy76 Thanks for your enthusiasm! 👍

It should be possible to adapt the batch processing script template I created for my `other_video_transcoding` project. It's available here:

https://github.com/lisamelton/other_video_transcoding/wiki/Batching

That's basically what I've done.

Does that help?

**Comment by geddy76** [comment]
That certainly points me in the right direction. First attempt is throwing errors, so it looks like I have some learning to do. Thanks very much!

**Comment by lisamelton** [comment]
@geddy76 Excellent! Let's keep this open in case you get stuck on something and need to ask questions. We can close it when everything is running smoothly.

**Comment by geddy76** [comment]
Appreciate it. Poking around in this. Full disclosure: I’ve never used Ruby before. I have a basic understanding of JavaScript and python, but that’s about as far as I go. Not asking for this to be spoon fed, just giving context. 

 I changed the last line of batch.rb to call hevc-transcode.rb instead of other-transcode.rb. That is the only change I made. That batch file, the actual hevc-transcode file and the queue.txt are all in my /usr/local/bin folder. I have two test episodes (mkv) in my user Movies folder, which the queue file points to. In terminal, I cd to /usr/local/bin and run ‘ruby batch.rb’ with no errors, but no apparent result; just a new prompt line. However, when I open the queue file, the first line has been deleted. So it’s doing something, it just doesn’t seem to be calling the hevc-transcode script.

**Comment by lisamelton** [comment]
@geddy76 Hmmmm, did you make the `hevc-transcode.rb` script executable? Like this:

```
chmod +x hevc-transcode.rb
```

And are you spelling it `hevc-transcode.rb` and not `hevc-transcode` in the batch script?

**Comment by geddy76** [comment]
Definitely appreciate the assistance on this. A few updates:

- Chmod doesn’t seem to do anything. No errors, but when I do Get Info, it still shows it as a Plain Text File for type. I have others in that folder that show as Unix Executable. 

- when I remove *ARGV from the last line of batch.rb, it will actually kick off HandbrakeCLI and get to work on a file. However, it would only do the first of the two files listed in the queue. 
- it’s actually not working in the last file listed in the queue. I added a third test file to the queue and it transcodes the first two but stops before working on the final. 

At this point, I can make this work. I’m not giving Handbrake any options at this point, just using your settings from hevc-transcode. And for the queue, I can just be sure to duplicate the last line, knowing it will stop on that one.

**Comment by skj-dev** [comment]
> ...No errors, but when I do Get Info, it still shows it as a Plain Text File...

This is correct, since it is still a text file. The `chmod +x file` changes the permissions of the file, setting the "execute bit". On UNIX/Linux systems (macOS is UNIX at the core) being able to "run" something is governed by the "execute bit". If you do a `ls -l file`, you will see the permissions on the file, and there should be an `x` in the owner/group/other columns. 

For example:

```
❯ touch foo
❯ ls -l foo
.rw-r--r-- 0 sean  6 Jul 18:45 foo
❯ chmod +x foo
❯ ls -l foo
.rwxr-xr-x 0 sean  6 Jul 18:45 foo
❯ chmod -x foo
❯ ls -l foo
.rw-r--r-- 0 sean  6 Jul 18:45 foo
```

> ...That batch file, the actual hevc-transcode file and the queue.txt are all in my /usr/local/bin folder...

In general, you only want to put programs in `/usr/local/bin`, and not use it as a working directory. Assuming `/usr/local/bin` is in your path (verifiable by typing `echo $PATH`, and looking for `/usr/local/bin` in the list), if you drop a file into `/usr/local/bin`, and the execute bit is on (i.e. `chmod +x /usr/local/bin/file`), then you can just run the file by its name. 

For example, if I have a file, `foo.rb`, and I do the following:

```
❯ chmod a+x foo.rb
❯ mv foo.rb /usr/local/bin/
```

I can then run `foo.rb` from anywhere by just typing `foo.rb`. 

Just wanted to give a couple pointers to things that sounded like they might be causing some confusion.

**Comment by lisamelton** [comment]
@geddy76 First, don't remove the `*ARGV` from the `batch.rb` script or you've never be able to add options at a later time.

Second, your last line listed in your `queue.txt file is not being processed because your last line isn't terminated with a carriage return. In your text editor, make sure your cursor is on a blank line when you're all the way at the end of the file. If the editor you're using is somehow "optimizing" that carriage return away, use a different editor.

I hope that helps.

**Comment by loshlee** [comment]
If you're using a Mac, you might be interested in applying Lisa's command lines using AppleScript droplets. I've made some for use with [more-video-transcoding](https://github.com/lisamelton/more-video-transcoding), but they can be used with varying amounts of modification with many types of command lines. Once you have customized the AppleScript, you can save it as an AppleScript Application using Script Editor and drop the appropriate source file or files onto its icon. 

[two-pass-detelecine-aggr-crop-mp4-out.applescript](https://gist.github.com/loshlee/32c9aca2fa45e241c652fc810772bca1)

**Comment by geddy76** [comment]
> This is correct, since it is still a text file. The `chmod +x file` changes the permissions of the file, setting the "execute bit". On UNIX/Linux systems (macOS is UNIX at the core) being able to "run" something is governed by the "execute bit". If you do a `ls -l file`, you will see the permissions on the file, and there should be an `x` in the owner/group/other columns.

Got it. I thought that would be visually reflected in Finder. 


> In general, you only want to put programs in `/usr/local/bin`, and not use it as a working directory. Assuming `/usr/local/bin` is in your path (verifiable by typing `echo $PATH`, and looking for `/usr/local/bin` in the list), if you drop a file into `/usr/local/bin`, and the execute bit is on (i.e. `chmod +x /usr/local/bin/file`), then you can just run the file by its name.
> 
> For example, if I have a file, `foo.rb`, and I do the following:
> 
> ```
> ❯ chmod a+x foo.rb
> ❯ mv foo.rb /usr/local/bin/
> ```
> 
> I can then run `foo.rb` from anywhere by just typing `foo.rb`.
> 
> Just wanted to give a couple pointers to things that sounded like they might be causing some confusion.

Definitely appreciate that guidance. Now that I’ve made it executable, I can indeed run the file from the initial Terminal prompt. I’ve moved the queue file to my home/user folder.

**Comment by geddy76** [comment]
> @geddy76 First, don't remove the `*ARGV` from the `batch.rb` script or you've never be able to add options at a later time.

I’ve verified several times that the script will only run for me if I’ve removed *ARGV. I’m way outside of my element, so I won’t begin to guess why. 

> Second, your last line listed in your `queue.txt file is not being processed because your last line isn't terminated with a carriage return.

That makes total sense and queue is working through all files now. 

Truly appreciate all the help on this!

**Comment by geddy76** [comment]
> If you're using a Mac, you might be interested in applying Lisa's command lines using AppleScript droplets. I've made some for use with [more-video-transcoding](https://github.com/lisamelton/more-video-transcoding), but they can be used with varying amounts of modification with many types of command lines. Once you have customized the AppleScript, you can save it as an AppleScript Application using Script Editor and drop the appropriate source file or files onto its icon.
> 
> [two-pass-detelecine-aggr-crop-mp4-out.applescript](https://gist.github.com/loshlee/32c9aca2fa45e241c652fc810772bca1)

Interesting. It’s been a couple years since I’ve messed around with AppleScript, though I used to absolutely love it. Thanks!

**Comment by lisamelton** [comment]
@geddy76 I'm glad everything is working! Do you want to close this issue now or shall I?

**Comment by geddy76** [comment]
I can close it. But if you ever determine why the *ARGV won’t allow the script to run, I’d love to hear. tomorrow I’ll give the original version of the batch script with other-transcode.

**Comment by geddy76** [comment]
I can close it. But if you ever figure out why I can’t run the script with ARGV included, I’d be interested. Tomorrow I’ll give the original batch script a try with other-transcode, which I already have installed.

**Comment by geddy76** [comment]
Confirming that when I run the original Batch script (calling other-transcode) it runs with the ARGV bit in there. Again, I’m not overly concerned, because I’m not passing any options along for batches (tv shows), but figured I’d pass the info along. 

Thanks again to both of you for the assistance.
